[[runners]]
  name = "Kubernetes Runner"
  url = "https://gitlab.com/ci"
  token = "{{ .gitlab_runner_token }}"
  executor = "kubernetes"
  privileged = true      [runners.kubernetes]
    namespace = "gitlab"

    [[runners.kubernetes.volumes.host_path]]
      name = "docker"
      mount_path = "/var/run/docker.sock"
      read_only = false
    [[runners.kubernetes.volumes.host_path]]
      name = "buildah"
      mount_path = "/var/lib/containers/"
      read_only = false
